name: Lint

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./EVASEAC
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '17.x'
      - name: Setup env
        run: npm install
      - name: Check lint
        run: npm run lint
